$schema: https://json-schema.org/draft/2020-12/schema
title: Program settings
description: |
  User settings for MUSE2. Note that these settings do **not** include model parameters, which
  are found in `model.toml` instead.

  All settings are optional. If the `settings.toml` file does not exist, the default settings will
  be used.

  The `settings.toml` file must be in the current working directory.
type: object
properties:
  log_level:
    type: string
    description: The program's log level
    default: info
    notes: Must be one of `error`, `warn`, `info`, `debug`, `trace` or `off` (case insensitive)
  overwrite:
    type: boolean
    description: Whether to overwrite output files by default
    default: false
  debug_model:
    type: boolean
    description: Whether to include extra debugging information in the model output
    default: false
    notes: |
      This includes raw values such as commodity balance duals, which may be useful for debugging
      the model or understanding results in more detail.
  results_root:
    type: string
    description: Results root path to save MUSE2 results
    default: "muse2_results"
    notes: Defaults to a "muse2_results" folder within the current working directory.
  graph_results_root:
    type: string
    description: Results root path to save MUSE2 graph outputs
    default: "muse2_graphs"
    notes: Defaults to a "muse2_graphs" folder within the current working directory.
