name: Update Rust toolchain
on:
  # HACK!!!!!!!!!!!!!
  push:
    branches: [fix-update-toolchain-workflow]
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: "0 0 * * mon"

env:
  GIT_TRACE: 1

jobs:
  update-rust-toolchain:
    name: "Update rust-toolchain"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: update rust toolchain
        uses: a-kenji/update-rust-toolchain@v1
        with:
          toolchain-path: ./rust-toolchain.toml
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
